baseURL = 'https://deeparena.github.io/website'
title = 'DeepArena'

# Language settings
contentDir = "content/zh"
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = false

[module]
proxy = "direct"
# uncomment line below for temporary local development of module
# replacements = "github.com/google/docsy -> ../../docsy"
[module.hugoVersion]
extended = true
min = "0.73.0"
[[module.imports]]
path = "github.com/google/docsy"
disable = false
[[module.imports]]
path = "github.com/google/docsy/dependencies"
disable = false

[languages]
[languages.zh]
languageName ="简体中文"
weight = 1
contentDir = "content/zh"
[languages.zh.params]
version_menu = "版本列表"
[languages.zh.menu]
[[languages.zh.menu.main]]
name = "文档"
weight = -101
pre = "<i class='fas fa-book pr-2'></i>"
url = "/docs/"
[[languages.zh.menu.main]]
name = "博客"
weight = -100
pre = "<i class='fas fa-rss pr-2'></i>"
url = "blog/"


[languages.en]
version_menu = "Versions"
languageName ="English"
contentDir = "content/en"
weight = 1
[languages.en.params]
version_menu = "Versions"
[languages.en.menu]
[[languages.en.menu.main]]
name = "Documentation"
weight = -101
pre = "<i class='fas fa-book pr-2'></i>"
url = "docs/"
[[languages.en.menu.main]]
name = "Blog"
weight = -100
pre = "<i class='fas fa-rss pr-2'></i>"
url = "blog/"



[markup]
[markup.goldmark]
[markup.goldmark.parser.attribute]
block = true
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
# See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
style = "tango"
# Uncomment if you want your chosen highlight style used for code blocks without a specified language
# guessSyntax = "true"

[params]
copyright = "12313"
privacy_policy = "123"
# Google Custom Search Engine ID. Remove or comment out to disable search.
gcs_engine_id = "d72aa9b2712488cc3"

# Enable Algolia DocSearch
algoli = false

# Enable Lunr.js offline search
offlineSearch = false
version = "master"
archived_version = false

[params.ui]
navbar_logo = true
sidebar_search_disable = false

[[params.versions]]
version = "master"
url = "https://deeparena.github.io/website"
prefix = "website"
#[[params.versions]]
#version = "master1"
#url = "http://localhost:1313/"

